#!/bin/tcsh -f


echo "      *******************      ****************       ******             "
echo "      *******************      ****************       ******             "
echo "             *****             ****        ****       ******             "
echo "             *****             ****                   ******             "
echo "             *****             ****                   ******             "
echo "             *****             ****        ****       ******             "
echo "             *****             ****************       ***************    "
echo "             *****             ****************       ***************    "


set my_work_dir = `pwd`

#Tool Initialization

if ($#argv != 1) then
	echo "Info: Please provide the csv file"
	exit 1
endif

if (! -f $argv[1] || $argv[1] == "-help") then
	if ($argv[1] != "-help") then
		echo "ERror: Cannot find csv file $argv[1]. EXiting..."
		exit 1
	else
		echo USAGE: ./vsdsynth \<csv file\>
		echo    
		echo         where \<csv file\> consists of 2 columns, below keyword being in 1st column and is case sensistive.
		echo
		echo         \<Design Name\> is the name of top level module
		echo
		echo         \<Output Directory\> is the name of output directory where you want to dump synthesis script, synthesized netlist and timing reports
		echo
		echo         \<Netlist Directory\> is the name of directory where all RTL netlist are present
	        echo
		echo         \<Early Library Path\> is the file path of the early cell library to be used for STA
		echo
		echo         \<Late Library Path\> is file path of the late cell library to be used for STA
		echo
		echo         \<Constraints file\> is csv file path of constraints to be used for STA
		exit 1
	endif
else
	#echo "Ankur"
	tclsh vsdsynth.tcl $argv[1]
endif








